on:
  push:
    branches:
    
    - main
  pull_request:
    branches:
    - main
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Build
      run: dotnet build --configuration Release
      working-directory: C:\Users\jvazq\Desktop\MortgageCalculatorRepo\Mortgage_Calculator\Mortgage_Calculator\Mortgage_Calculator.csproj
    - name: Test
      run: dotnet test --configuration Release --no-build
